version: '3.9'
services:
  php:
    build:
      context: ./docker/php
    volumes:
      - './www:/var/www/html'

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - './www:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    ports:
      - 80:80
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
    volumes:
      - './docker/mysql:/var/lib/mysql'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
    depends_on:
    - mysql