version: '3.3'
services:
  php:
    build:
      context: ./docker/php
    volumes:
      - './www:/var/www/html'

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - './www:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    ports:
      - ${SERVER_PORT}:80
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=Europe/Moscow
    volumes:
      - './docker/mysql/data:/var/lib/mysql'
      - './docker/mysql/backup:/tmp/backup'
      - './docker/mysql/entrypoint:/docker-entrypoint-initdb.d'
    command: --init-file /docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - ${PHP_MY_ADMIN_PORT}:80
    environment:
      PMA_HOST: mysql
      MYSQL_USERNAME: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
    - mysql
